language: php

php:
    - 7.0
    - 7.1
    - 7.2

matrix:
    allow_failures:
        - php: 7.0

install: composer install

script: phpunit --configuration phpunit.xml.dist --coverage-text

after_success:
    - ./success.sh